#!/bin/bash

# Start the xpra session, if it's not running and attach to it.
PROCESS_NUM=$(ps -ef | grep "xpra" | grep -v "grep" | wc -l)
if [ $PROCESS_NUM -eq 0 ]; then
        # Start xpra session
	xpra start :0 & sleep 5 ; DISPLAY=:0 /home/docker/tor-browser_en-US/start-tor-browser &
  #xpra start :0 & sleep 5 ; DISPLAY=:0 /home/docker/tor-browser_en-US/App/Firefox/firefox -no-remote -profile /tmp/tor-browser_en-US/Data/profile &
fi

# Attach the xpra session 0
xpra attach :0
